#' Visualize Tree Structure from ICE-Based Model
#'
#' Plots the hierarchical structure of a decision tree built on ICE curves using \code{ggplot2},
#' including node labels and connecting edges. This provides an overview of the tree topology without displaying ICE curves.
#'
#' @param tree A list-of-lists structure returned by \code{compute_tree()}, containing \code{Node} objects organized by depth.
#' @param layout A \code{data.frame} generated by \code{prepare_tree_layout()}, specifying coordinates and labels for each node.
#'
#' @return A \code{ggplot} object showing the tree structure, including:
#' \itemize{
#'   \item Labeled nodes indicating the feature and threshold (or "Leaf").
#'   \item Directed edges linking parent to children.
#'   \item Distinct colors per tree depth.
#' }
#'
#' @details
#' Each node is represented by a labeled box, and arrows indicate parent-child relationships.
#' Colors are automatically assigned to indicate depth level.
#'
#' Useful for debugging or structural analysis of interpretable tree models built using ICE data.
#'
#' @seealso \code{\link{prepare_tree_layout}}, \code{\link{compute_tree}}
#'
#' @export
plot_tree_structure <- function(tree, layout) {
  edges = data.frame()

  for (depth in seq_along(tree)) {
    nodes = tree[[depth]]
    if (depth < length(tree)) {
      for (i in seq_along(nodes)) {
        node = nodes[[i]]
        if (!is.null(node)) {
          left.child = node$children$left.child
          right.child = node$children$right.child

          if (!is.null(left.child)) {
            edges = rbind(edges, data.frame(
              x = layout$x[layout$id == paste0(depth, "_", i)],
              y = layout$y[layout$id == paste0(depth, "_", i)],
              xend = layout$x[layout$id == paste0(depth+1, "_", (i-1)*2+1)],
              yend = layout$y[layout$id == paste0(depth+1, "_", (i-1)*2+1)]
            ))
          }

          if (!is.null(right.child)) {
            edges = rbind(edges, data.frame(
              x = layout$x[layout$id == paste0(depth, "_", i)],
              y = layout$y[layout$id == paste0(depth, "_", i)],
              xend = layout$x[layout$id == paste0(depth+1, "_", (i-1)*2+2)],
              yend = layout$y[layout$id == paste0(depth+1, "_", (i-1)*2+2)]
            ))
          }
        }
      }
    }
  }

  # Set color for each depth
  n.depths = length(unique(layout$depth))
  palette = scales::hue_pal()(n.depths)

  layout$color = palette[as.numeric(as.factor(layout$depth))]

  p = ggplot() +
    geom_segment(data = edges, aes(x = x, y = y, xend = xend, yend = yend),
                 arrow = arrow(length = unit(0.15, "cm")),
                 size = 0.7, color = "grey30") +
    geom_label(data = layout, aes(x = x, y = y, label = label, fill = as.factor(depth)),
               color = "black", label.size = 0.3, label.padding = unit(0.2, "lines")) +
    scale_fill_manual(values = palette) +
    theme_void() +
    theme(legend.position = "none")

  return(p)
}
